### ISSUE TITLE
[Quetion]  Inquiry about Performance Bound in Your Paper

### ISSUE THREAD

**Issue by linhlpv** [junming-yang/MOAN#1]
Hi @junming-yang ,
I hope you're doing well! Firstly, kudos on your outstanding work and the paper.

I've thoroughly gone through your paper and came across a point in section 5 where you mention, "Our bound is tighter than MOPO." However, I couldn't find a detailed analysis supporting this claim. I attempted to validate it independently but couldn't replicate the results. Could you kindly provide more insight into the reasoning behind this assertion?

Thanks a bunch and have a fantastic day!

Best regards,
Linh

**Comment by junming-yang** [comment]
Hi Linh,

Thank you for your thorough review and your insightful question regarding our paper's claim about the tightness of our bound compared to MOPO.

The assertion regarding our bound being tighter specifically refers to the theoretical aspect, where the lower bound, denoted by return $\mathcal{J}(\pi, \mathcal{M})$ in Eq. 4, signifies a higher return value in the stage of online evaluation (scores in Table 1). 

Best regards,
Junming Yang

**Comment by linhlpv** [comment]
Hi @junming-yang,

Thank you for your answer. It makes sense to me :+1: :blush:

Best,
Linh
